### Minimum rule-set to solve paper-sparqldl-Q3.rq

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

## rdfs9 (RDF 1.1 Semantics)
INSERT { ?a a ?y }
WHERE { ?x rdfs:subClassOf ?y .
        ?a a ?x } ;

## rule6b (complementOf disjoint, from SPARQL test set paper-sparqldl-Q3.rq)
# MJR: Not sure if this is true, but the SPARQL entailment test assumes so

INSERT { ?u owl:complementOf ?v }
WHERE { ?u owl:disjointWith ?v } ;

