# OWL 2 RL Rules

# From "OWL 2 Web Ontology Language Profiles (Second Edition), W3C Recommendation 11 December 2012"
# http://www.w3.org/TR/owl2-profiles/

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX : <http://instans.org/>

### Table 6. The Semantics of Classes

# @name cls-svf2
INSERT { ?u a ?x }
WHERE { ?x owl:someValuesFrom owl:Thing ;
           owl:onProperty ?p .
        ?u ?p ?v } ;

### Table 7: The Semantics of Class Axioms

# @name cax-sco (also rdfs9, RDF 1.1 Semantics)
INSERT { ?a a ?y }
WHERE { ?x rdfs:subClassOf ?y .
        ?a a ?x } ;

### Table 9: The Semantics of Schema Vocabulary

# @name scm-eqc1 (also rdfp12a, rdfp12b, subsumption on equivalentClass, ter Horst)
INSERT { ?v rdfs:subClassOf ?w .
         ?w rdfs:subClassOf ?v }
WHERE { ?v owl:equivalentClass ?w } ;

