### Minimum rule-set to solve rdfs07.rq

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

## rdfs3 (RDF 1.1 Semantics)
INSERT { ?o a ?c }
WHERE { ?s ?p ?o .
        ?p rdfs:range ?c } ;
