# rho-df rules

# Sources:
# Munoz 2007: http://link.springer.com/chapter/10.1007/978-3-540-72667-8_6
# Munoz 2009: http://www.sciencedirect.com/science/article/pii/S1570826809000249

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

## 3.(b) Subclass (Munoz 2007, also rdfs9 from RDF 1.1 Semantics)
INSERT { ?a a ?y }
WHERE { ?x rdfs:subClassOf ?y .
        ?a a ?x } ;

## 7.(a) Subclass reflexivity (Munoz 2007):
INSERT { ?a rdfs:subClassOf ?a .
         ?b rdfs:subClassOf ?b }
WHERE { ?a rdfs:subClassOf ?b } ;

