
# Special rule to resolve test: simple6

# Note: Three rules are needed, because INSTANS does not currently support wildcards in property path matching.
# Once the support is added, a single more generic query can be created with a property path expression.

# OWL-rules taylored to correspond to the SPARQL entailment tests in:
# http://www.w3.org/2009/sparql/implementations/

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

## extra10: simple6.rq

INSERT {
  ?a a [ a owl:Restriction ;
           owl:onProperty ?p ;
	   owl:allValuesFrom [
	     a owl:Class ;
             owl:unionOf ( ?c0 ?c1 ?c2 ) ] ] }
WHERE { ?c0 a owl:Class .
        ?c1 a owl:Class .
        ?c2 a owl:Class .
        ?p a owl:ObjectProperty .
	?a ?p [ a ?c0 , ?c1, ?c2 ] .
	FILTER (!sameTerm(?c0,?c1))
	FILTER (!sameTerm(?c0,?c2))
	FILTER (!sameTerm(?c2,?c1))
	FILTER (!isBlank(?c0))
	FILTER (!isBlank(?c1))
	FILTER (!isBlank(?c2)) } ; 

## extra11: simple6.rq

INSERT {
  ?a a [ a owl:Restriction ;
           owl:onProperty ?p ;
	   owl:allValuesFrom [
	     a owl:Class ;
             owl:unionOf ( ?c0 ?c1 ?c2 ) ] ] }
WHERE { ?c0 a owl:Class .
        ?c1 a owl:Class .
        ?c2 a owl:Class .
        ?p a owl:ObjectProperty .
	?a ?p [ ?p [ a ?c0 , ?c1, ?c2 ] ] .
	FILTER (!sameTerm(?c0,?c1))
	FILTER (!sameTerm(?c0,?c2))
	FILTER (!sameTerm(?c2,?c1))
	FILTER (!isBlank(?c0))
	FILTER (!isBlank(?c1))
	FILTER (!isBlank(?c2)) } ; 

## extra12: simple6.rq

INSERT {
  ?a a [ a owl:Restriction ;
           owl:onProperty ?p ;
	   owl:allValuesFrom [
	     a owl:Class ;
             owl:unionOf ( ?c0 ?c1 ?c2 ) ] ] }
WHERE { ?c0 a owl:Class .
        ?c1 a owl:Class .
        ?c2 a owl:Class .
        ?p a owl:ObjectProperty .
	?a ?p [ ?p [ ?p [ a ?c0 , ?c1, ?c2 ] ] ] .
	FILTER (!sameTerm(?c0,?c1))
	FILTER (!sameTerm(?c0,?c2))
	FILTER (!sameTerm(?c2,?c1))
	FILTER (!isBlank(?c0))
	FILTER (!isBlank(?c1))
	FILTER (!isBlank(?c2)) } ; 
