# simple4: Sample rule to produce the same result as the test
# without pre-processing to a permutative list.

# OWL-rules taylored to correspond to the SPARQL entailment tests in:
# http://www.w3.org/2009/sparql/implementations/

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://example.org/test#>

SELECT DISTINCT ?x
WHERE { { ?x a :B } UNION { ?x a :C } } ; 
