### Minimum rule-set to solve sparqldl-13.rq

# Note: The combination of rdfp5a+rdfp11 also materializes the correct answers, but in double.

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

### Table 4. The Semantics of Equality

# @name eq-sym (also rdfp6, ter Horst)
INSERT { ?y owl:sameAs ?x }
WHERE { ?x owl:sameAs ?y } ;

# @name eq-rep-o
INSERT { ?s ?p ?o2 }
WHERE { ?o owl:sameAs ?o2 .
        ?s ?p ?o } ;
