# OWL 2 RL Rules

# From "OWL 2 Web Ontology Language Profiles (Second Edition), W3C Recommendation 11 December 2012"
# http://www.w3.org/TR/owl2-profiles/

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX : <http://instans.org/>

### Table 4. The Semantics of Equality

# @name eq-ref (partially rdfp5, ter Horst)
INSERT { ?s owl:sameAs ?s .
         ?p owl:sameAs ?p .
	 ?o owl:sameAs ?o }
WHERE { ?s ?p ?o } ;

